# Generated by Django 3.0.3 on 2020-02-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediapost', '0001_initial'),
        ('webarticles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='urls',
        ),
        migrations.RemoveField(
            model_name='site',
            name='urls',
        ),
        migrations.RemoveField(
            model_name='sitetag',
            name='sites',
        ),
        migrations.RemoveField(
            model_name='article',
            name='site_id',
        ),
        migrations.RemoveField(
            model_name='url',
            name='canonical',
        ),
        migrations.RemoveField(
            model_name='url',
            name='expanded',
        ),
        migrations.RemoveField(
            model_name='url',
            name='html',
        ),
        migrations.RemoveField(
            model_name='url',
            name='status_code',
        ),
        migrations.AddField(
            model_name='url',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='url_posts', to='socialmediapost.SocialMediaPost'),
        ),
        migrations.DeleteModel(
            name='AlternateDomain',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
        migrations.DeleteModel(
            name='SiteTag',
        ),
    ]
