# Generated by Django 3.0.3 on 2020-02-25 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webarticles', '0003_auto_20200225_1451'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
        migrations.AlterModelTable(
            name='url',
            table='url',
        ),
    ]
