# Generated by Django 3.0.3 on 2020-02-26 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webarticles', '0004_auto_20200225_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('base_url', models.CharField(max_length=511, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='article',
            old_name='canonical_url',
            new_name='expanded_url',
        ),
        migrations.AddField(
            model_name='url',
            name='scraped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='url',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webarticles.Site'),
        ),
    ]
