# Generated by Django 3.0.3 on 2020-02-26 06:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webarticles', '0005_auto_20200225_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='expanded_url',
            new_name='canonical',
        ),
        migrations.RemoveField(
            model_name='article',
            name='date_captured',
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None),
        ),
        migrations.AddField(
            model_name='url',
            name='canonical',
            field=models.CharField(max_length=2083, null=True),
        ),
    ]
