# Generated by Django 3.0.3 on 2020-02-26 06:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webarticles', '0006_auto_20200226_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='article',
            name='group_id',
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None),
        ),
        migrations.AddField(
            model_name='article',
            name='lang',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
