# Generated by Django 3.0.3 on 2020-02-26 06:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webarticles', '0007_auto_20200226_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
