# Generated by Django 3.0.3 on 2020-02-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webarticles', '0008_article_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='expanded',
            field=models.CharField(max_length=2083, null=True, unique=True),
        ),
    ]
