# Generated by Django 3.0.3 on 2020-02-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webarticles', '0011_site_crawl'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='canonical',
            field=models.CharField(max_length=2083, null=True, unique=True),
        ),
    ]
