# Generated by Django 3.0.3 on 2020-02-23 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Countries',
            new_name='Country',
        ),
        migrations.RenameModel(
            old_name='SocialMediaPosts',
            new_name='SocialMediaPost',
        ),
    ]
