# Generated by Django 3.0.3 on 2020-02-24 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200223_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediapost',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='socialmediapost',
            name='location',
        ),
        migrations.RemoveField(
            model_name='socialmediapost',
            name='lon',
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='reposted_by',
            field=models.ManyToManyField(blank=True, related_name='reposted_by', to='common.SocialMediaUser'),
        ),
        migrations.AddField(
            model_name='socialmediauser',
            name='country',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Country'),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='sentiment',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
