# Generated by Django 3.0.3 on 2020-02-24 14:51

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20200223_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmediapost',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='socialmediapost',
            name='filtered_words',
        ),
        migrations.RemoveField(
            model_name='socialmediapost',
            name='screen_name',
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.SocialMediaUser'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='hashtags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='reply_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='in_reply_to_post_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='in_reply_to_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='post_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='sentiment',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='user_mentions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(blank=True), null=True, size=None),
        ),
    ]
