# Generated by Django 3.0.3 on 2020-02-24 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20200224_0851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='SocialMediaCountry',
        ),
        migrations.RemoveField(
            model_name='socialmediauser',
            name='posts',
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.SocialMediaUser'),
        ),
        migrations.AlterField(
            model_name='socialmediauser',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.SocialMediaCountry'),
        ),
    ]
