# Generated by Django 3.0.3 on 2020-02-25 19:45

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialmediauser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None)),
                ('post_id', models.BigIntegerField(blank=True, null=True)),
                ('in_reply_to_user_id', models.BigIntegerField(blank=True, null=True)),
                ('in_reply_to_post_id', models.BigIntegerField(blank=True, null=True)),
                ('lang', models.CharField(max_length=20, null=True)),
                ('reply_count', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True)),
                ('sentiment', models.CharField(max_length=20, null=True)),
                ('service', models.CharField(max_length=20)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialmediauser.SocialMediaUser')),
                ('reposted_by', models.ManyToManyField(blank=True, related_name='reposted_by', to='socialmediauser.SocialMediaUser')),
                ('user_mentions', models.ManyToManyField(blank=True, related_name='user_mentions', to='socialmediauser.SocialMediaUser')),
            ],
            options={
                'db_table': 'socialmediapost',
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, unique=True)),
                ('posts', models.ManyToManyField(blank=True, related_name='posts', to='socialmediapost.SocialMediaPost')),
            ],
            options={
                'db_table': 'hashtag',
            },
        ),
    ]
